---
title: "mp4"
output: html_document
---
 
```{r}
library(mdsr)
library(RMySQL)
db <- dbConnect_scidb(dbname = "imdb")
yr67 <- "SELECT mi1.movie_id, 
			      mi1.info AS gross, 
            mi2.info, 
            t.title
      FROM title AS t
      JOIN movie_info AS mi1 ON
      	mi1.movie_id = t.id
      JOIN movie_info AS mi2 ON 
      	mi2.movie_id = mi1.movie_id
      WHERE mi1.info_type_id = 107
      		AND mi2.info_type_id = 8
      		AND mi2.info = 'USA'
          AND t.production_year = 1967"; 
dbyr67 <- dbGetQuery(db, yr67)

totalgross67 <- dbyr67 %>%
  filter(grepl("\\(USA\\)|worldwide|Worldwide", gross)) %>%
  mutate(gross_string = str_extract(gross, "^\\$[0-9]+,[0-9]{3},[0-9]{3}"),
         gross = parse_number(gross_string)) %>%
  group_by(movie_id, title) %>%
  summarise(sum_gross = sum(gross)) %>%
  arrange(desc(sum_gross)) 

#join with other tables to get directors 
alldirectors_67 <- "SELECT movie_id, person_id,  gender, production_year,
COUNT(DISTINCT(person_id)) AS totaldirectors
FROM imdb.cast_info AS ci 
JOIN name AS n ON n.id = ci.person_id
JOIN title AS t ON t.id = ci.movie_id
WHERE role_id = 8
AND production_year = 1967;"
dballdirectors_67 <- dbGetQuery(db, alldirectors_67)

#find ratio of female directors
femaledirectors_67 <- "SELECT movie_id, person_id,  gender, production_year,
COUNT(Distinct person_id) AS femaledirectors 
FROM imdb.cast_info AS ci 
JOIN name AS n ON n.id = ci.person_id
JOIN title AS t ON t.id = ci.movie_id
WHERE role_id = 8
AND production_year = 1967
AND gender = 'f';"
dbfemaledirectors_67 <- dbGetQuery(db, femaledirectors_67)
#use proportion of female character than finding leading female 
#388

dbft67 <- inner_join(dbfemaledirectors_67, totalgross67)
#no results is shown, meaning there are no female directors 

prop67 <- dbfemaledirectors_67 %>%
  mutate(propdirectors = dbfemaledirectors_67$femaledirectors/dballdirectors_67$totaldirectors)
```

```{r}
library(mdsr)
library(RMySQL)
db <- dbConnect_scidb(dbname = "imdb")
yr77 <- "SELECT mi1.movie_id, 
			      mi1.info AS gross, 
            mi2.info, 
            t.title
      FROM title AS t
      JOIN movie_info AS mi1 ON
      	mi1.movie_id = t.id
      JOIN movie_info AS mi2 ON 
      	mi2.movie_id = mi1.movie_id
      WHERE mi1.info_type_id = 107
      		AND mi2.info_type_id = 8
      		AND mi2.info = 'USA'
          AND t.production_year = 1977"; 
dbyr77 <- dbGetQuery(db, yr77)

totalgross77 <- dbyr77 %>%
  filter(grepl("\\(USA\\)|worldwide|Worldwide", gross)) %>%
  mutate(gross_string = str_extract(gross, "^\\$[0-9]+,[0-9]{3},[0-9]{3}"),
         gross = parse_number(gross_string)) %>%
  group_by(movie_id, title) %>%
  summarise(sum_gross = sum(gross)) %>%
  arrange(desc(sum_gross)) 

#join with other tables to get directors 
alldirectors_77 <- "SELECT movie_id, person_id,  gender, production_year,
COUNT(DISTINCT(person_id)) AS totaldirectors
FROM imdb.cast_info AS ci 
JOIN name AS n ON n.id = ci.person_id
JOIN title AS t ON t.id = ci.movie_id
WHERE role_id = 8
AND production_year = 1977;"
dballdirectors_77 <- dbGetQuery(db, alldirectors_77)

#find ratio of female directors
femaledirectors_77 <- "SELECT movie_id, person_id,  gender, production_year,
COUNT(Distinct person_id) AS femaledirectors 
FROM imdb.cast_info AS ci 
JOIN name AS n ON n.id = ci.person_id
JOIN title AS t ON t.id = ci.movie_id
WHERE role_id = 8
AND production_year = 1977
AND gender = 'f';"
dbfemaledirectors_77 <- dbGetQuery(db, femaledirectors_77)
#use proportion of female character than finding leading female 
#388

dbft77 <- inner_join(dbfemaledirectors_77, totalgross77)
#no results is shown, meaning there are no female directors 

prop77 <- dbfemaledirectors_77 %>%
  mutate(propdirectors = dbfemaledirectors_77$femaledirectors/dballdirectors_77$totaldirectors)
```
```{r}
library(mdsr)
library(RMySQL)
db <- dbConnect_scidb(dbname = "imdb")
yr87 <- "SELECT mi1.movie_id, 
			      mi1.info AS gross, 
            mi2.info, 
            t.title
      FROM title AS t
      JOIN movie_info AS mi1 ON
      	mi1.movie_id = t.id
      JOIN movie_info AS mi2 ON 
      	mi2.movie_id = mi1.movie_id
      WHERE mi1.info_type_id = 107
      		AND mi2.info_type_id = 8
      		AND mi2.info = 'USA'
          AND t.production_year = 1987"; 
dbyr87 <- dbGetQuery(db, yr87)

totalgross87 <- dbyr87 %>%
  filter(grepl("\\(USA\\)|worldwide|Worldwide", gross)) %>%
  mutate(gross_string = str_extract(gross, "^\\$[0-9]+,[0-9]{3},[0-9]{3}"),
         gross = parse_number(gross_string)) %>%
  group_by(movie_id, title) %>%
  summarise(sum_gross = sum(gross)) %>%
  arrange(desc(sum_gross)) 

#join with other tables to get directors 
alldirectors_87 <- "SELECT movie_id, person_id,  gender, production_year,
COUNT(DISTINCT(person_id)) AS totaldirectors
FROM imdb.cast_info AS ci 
JOIN name AS n ON n.id = ci.person_id
JOIN title AS t ON t.id = ci.movie_id
WHERE role_id = 8
AND production_year = 1967;"
dballdirectors_87 <- dbGetQuery(db, alldirectors_87)

#find ratio of female directors
femaledirectors_87 <- "SELECT movie_id, person_id,  gender, production_year,
COUNT(Distinct person_id) AS femaledirectors 
FROM imdb.cast_info AS ci 
JOIN name AS n ON n.id = ci.person_id
JOIN title AS t ON t.id = ci.movie_id
WHERE role_id = 8
AND production_year = 1987
AND gender = 'f';"
dbfemaledirectors_87 <- dbGetQuery(db, femaledirectors_87)
#use proportion of female character than finding leading female 
#388

dbft87 <- inner_join(dbfemaledirectors_87, totalgross87)
#no results is shown, meaning there are no female directors 

prop87 <- dbfemaledirectors_87 %>%
  mutate(propdirectors = dbfemaledirectors_87$femaledirectors/dballdirectors_87$totaldirectors)
```

```{r}
library(mdsr)
library(RMySQL)
db <- dbConnect_scidb(dbname = "imdb")
yr97 <- "SELECT mi1.movie_id, 
			      mi1.info AS gross, 
            mi2.info, 
            t.title
      FROM title AS t
      JOIN movie_info AS mi1 ON
      	mi1.movie_id = t.id
      JOIN movie_info AS mi2 ON 
      	mi2.movie_id = mi1.movie_id
      WHERE mi1.info_type_id = 107
      		AND mi2.info_type_id = 8
      		AND mi2.info = 'USA'
          AND t.production_year = 1997"; 
dbyr97 <- dbGetQuery(db, yr97)

totalgross97 <- dbyr97 %>%
  filter(grepl("\\(USA\\)|worldwide|Worldwide", gross)) %>%
  mutate(gross_string = str_extract(gross, "^\\$[0-9]+,[0-9]{3},[0-9]{3}"),
         gross = parse_number(gross_string)) %>%
  group_by(movie_id, title) %>%
  summarise(sum_gross = sum(gross)) %>%
  arrange(desc(sum_gross)) 

#join with other tables to get directors 
alldirectors_97 <- "SELECT movie_id, person_id,  gender, production_year,
COUNT(DISTINCT(person_id)) AS totaldirectors
FROM imdb.cast_info AS ci 
JOIN name AS n ON n.id = ci.person_id
JOIN title AS t ON t.id = ci.movie_id
WHERE role_id = 8
AND production_year = 1997;"
dballdirectors_97 <- dbGetQuery(db, alldirectors_97)

#find ratio of female directors
femaledirectors_97 <- "SELECT movie_id, person_id,  gender, production_year,
COUNT(Distinct person_id) AS femaledirectors 
FROM imdb.cast_info AS ci 
JOIN name AS n ON n.id = ci.person_id
JOIN title AS t ON t.id = ci.movie_id
WHERE role_id = 8
AND production_year = 1997
AND gender = 'f';"
dbfemaledirectors_97 <- dbGetQuery(db, femaledirectors_97)
#use proportion of female character than finding leading female 
#388

dbft97 <- inner_join(dbfemaledirectors_97, totalgross97)
#no results is shown, meaning there are no female directors 

prop97 <- dbfemaledirectors_97 %>%
  mutate(propdirectors = dbfemaledirectors_67$femaledirectors/dballdirectors_67$totaldirectors)
```

```{r}
library(mdsr)
library(RMySQL)
db <- dbConnect_scidb(dbname = "imdb")
yr07 <- "SELECT mi1.movie_id, 
			      mi1.info AS gross, 
            mi2.info, 
            t.title
      FROM title AS t
      JOIN movie_info AS mi1 ON
      	mi1.movie_id = t.id
      JOIN movie_info AS mi2 ON 
      	mi2.movie_id = mi1.movie_id
      WHERE mi1.info_type_id = 107
      		AND mi2.info_type_id = 8
      		AND mi2.info = 'USA'
          AND t.production_year = 2007"; 
dbyr07 <- dbGetQuery(db, yr07)

totalgross07 <- dbyr07 %>%
  filter(grepl("\\(USA\\)|worldwide|Worldwide", gross)) %>%
  mutate(gross_string = str_extract(gross, "^\\$[0-9]+,[0-9]{3},[0-9]{3}"),
         gross = parse_number(gross_string)) %>%
  group_by(movie_id, title) %>%
  summarise(sum_gross = sum(gross)) %>%
  arrange(desc(sum_gross)) 

#join with other tables to get directors 
alldirectors_07 <- "SELECT movie_id, person_id,  gender, production_year,
COUNT(DISTINCT(person_id)) AS totaldirectors
FROM imdb.cast_info AS ci 
JOIN name AS n ON n.id = ci.person_id
JOIN title AS t ON t.id = ci.movie_id
WHERE role_id = 8
AND production_year = 2007;"
dballdirectors_07 <- dbGetQuery(db, alldirectors_07)

#find ratio of female directors
femaledirectors_07 <- "SELECT movie_id, person_id,  gender, production_year,
COUNT(Distinct person_id) AS femaledirectors 
FROM imdb.cast_info AS ci 
JOIN name AS n ON n.id = ci.person_id
JOIN title AS t ON t.id = ci.movie_id
WHERE role_id = 8
AND production_year = 2007
AND gender = 'f';"
dbfemaledirectors_07 <- dbGetQuery(db, femaledirectors_07)
#use proportion of female character than finding leading female 
#388

dbft07 <- inner_join(dbfemaledirectors_07, totalgross07)
#no results is shown, meaning there are no female directors 

prop07 <- dbfemaledirectors_07 %>%
  mutate(propdirectors = dbfemaledirectors_07$femaledirectors/dballdirectors_07$totaldirectors)
```



```{r}
library(mdsr)
library(RMySQL)
db <- dbConnect_scidb(dbname = "imdb")
yr17 <- "SELECT mi1.movie_id, 
			      mi1.info AS gross, 
            mi2.info, 
            t.title
      FROM title AS t
      JOIN movie_info AS mi1 ON
      	mi1.movie_id = t.id
      JOIN movie_info AS mi2 ON 
      	mi2.movie_id = mi1.movie_id
      WHERE mi1.info_type_id = 107
      		AND mi2.info_type_id = 8
      		AND mi2.info = 'USA'
          AND t.production_year = 2017"; 
dbyr17 <- dbGetQuery(db, yr17)

totalgross17 <- dbyr17 %>%
  filter(grepl("\\(USA\\)|worldwide|Worldwide", gross)) %>%
  mutate(gross_string = str_extract(gross, "^\\$[0-9]+,[0-9]{3},[0-9]{3}"),
         gross = parse_number(gross_string)) %>%
  group_by(movie_id, title) %>%
  summarise(sum_gross = sum(gross)) %>%
  arrange(desc(sum_gross)) 

#join with other tables to get directors 
alldirectors_17 <- "SELECT movie_id, person_id,  gender, production_year,
COUNT(DISTINCT(person_id)) AS totaldirectors
FROM imdb.cast_info AS ci 
JOIN name AS n ON n.id = ci.person_id
JOIN title AS t ON t.id = ci.movie_id
WHERE role_id = 8
AND production_year = 2017;"
dballdirectors_17 <- dbGetQuery(db, alldirectors_17)

#find ratio of female directors
femaledirectors_17 <- "SELECT movie_id, person_id,  gender, production_year,
COUNT(Distinct person_id) AS femaledirectors 
FROM imdb.cast_info AS ci 
JOIN name AS n ON n.id = ci.person_id
JOIN title AS t ON t.id = ci.movie_id
WHERE role_id = 8
AND production_year = 2017
AND gender = 'f';"
dbfemaledirectors_17 <- dbGetQuery(db, femaledirectors_17)
#use proportion of female character than finding leading female 
#388

dbft17 <- inner_join(dbfemaledirectors_17, totalgross17)
#no results is shown, meaning there are no female directors 

prop17 <- dbfemaledirectors_17 %>%
  mutate(propdirectors = dbfemaledirectors_17$femaledirectors/dballdirectors_17$totaldirectors)
```

```{r}
library(dplyr)
allyears<- merge(prop17, prop07, all=TRUE)
allyears1<-merge(allyears, prop97, all = TRUE)
allyears2<-merge(allyears1, prop87, all = TRUE)
allyears3<-merge(allyears2, prop77, all = TRUE)
allyearsfinal<-merge(allyears3, prop67, all = TRUE)
```
  
 1967, 2017
 3. 2017: no. of female directors, writors, cinematopgraphers, producers, editors in top 100 films
 
 #hypothesis1
#even though women's roles in film industry is becoming more prominent as seen in the increasing number of female directors and increasing activism for gender rights, there's still a big gender gap. 
#social events 